[registry]
default = "crates-io"
global-credential-providers = ["cargo:token"]

[registries.opif-opif]
index = "sparse+https://cargo.cnb.cool/IGIPME/OPIF/opif/-/packages/"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[env]
CARGO_WORKSPACE_DIR = { value = ".", relative = true }