apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openpicl
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CFPIF/OpenPICL.git
    targetRevision: main
    path: charts/openpicl
    helm:
      releaseName: openpicl
      valueFiles:
        - values.yaml
      values: |
        studio:
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: openpicl
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/imagePullPolicy