[package]
name = "nebula-protos"
description = "Nebula Protocol Crate"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
readme = "README.md"

[package.metadata]
publish = ["cargo-hosted"]

[dependencies]
serde = { workspace = true, features = ["derive"] }