apiVersion: v1
kind: Service
metadata:
  name: webide
spec:
  selector:
    app: webide
  ports:
    - name: http
      port: 3002
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webide
spec:
  selector:
    matchLabels:
      app: webide
  template:
    metadata:
      labels:
        app: webide
    spec:
      containers:
        - name: webide
          image: webide
          ports:
            - containerPort: 3002