set windows-shell := ["powershell.exe"]
export RUST_BACKTRACE := "1"

# 展示可用的命令
@just:
    just --list

# 构建本地依赖（common 库 Chart）
deps:
    helm dependency build openpicl

# 检查 Helm Chart（默认值、最小部署、生产部署）
lint: deps
    helm lint openpicl --strict
    helm lint openpicl --strict -f openpicl/values-minimal.yaml
    helm lint openpicl --strict -f openpicl/values-prod.yaml

# 本地渲染模板，例如 just template values-prod.yaml
template values="values.yaml": deps
    helm template openpicl openpicl -f openpicl/{{values}}

# 打包 Helm Chart
package: deps
    helm package openpicl

# 登录 Helm 仓库
login token:
    helm registry login -u admin -p {{token}} 117.50.75.30:8080

# 发布 Helm Chart
publish version:
    helm push openpicl-{{version}}.tgz oci://117.50.75.30:8080/openpicl_helm
