set windows-shell := ["powershell.exe"]
export RUST_BACKTRACE := "1"

# 展示可用的命令
@just:
    just --list

# 检查 Helm Chart
lint:
    helm lint openpicl
    helm lint openpicl-full

# 本地渲染模板
template:
    helm template openpicl
    helm template openpicl-full

# 打包 Helm Chart
package:
    helm package openpicl
    helm package openpicl-full

# 登录 Helm 仓库
login token:
    helm registry login -u cnb -p {{token}} helm.cnb.cool

# 发布 Helm Chart
publish version:
    helm push openpicl-{{version}}.tgz oci://helm.cnb.cool/igipme/opif/openpicl
    helm push openpicl-full-{{version}}.tgz oci://helm.cnb.cool/igipme/opif/openpicl