set windows-shell := ["powershell.exe"]
export RUST_BACKTRACE := "1"

# 展示可用的命令
@just:
    just --list

# 启动 Studio，非热重载
run:
    cargo leptos serve

# 启动 Studio，热重载
reload:
    cargo leptos watch

# 运行 Rust 测试
test:
    cargo test

# 运行 Cargo Check
check:
    cargo check -p app
    cargo check -p frontend
    cargo check -p protocol
    cargo check -p renderer
    cargo check -p server
    cargo check -p worker

# 调用 rustfmt 工具
fmt:
    cargo fmt --all -- --check

# 调用 clippy 工具
clippy:
    cargo clippy -p app -- -D warnings
    cargo clippy -p frontend -- -D warnings
    cargo clippy -p protocol -- -D warnings
    cargo clippy -p renderer -- -D warnings
    cargo clippy -p server -- -D warnings
    cargo clippy -p worker -- -D warnings

# 清理构建产物
clean:
    cargo clean

# 登录 Harbor 制品库
login token:
    docker login -u admin -p {{token}} 117.50.75.30:8080

# 构建并推送制品
publish tag:
    docker build -t 117.50.75.30:8080/cfpif/openpicl.studio:latest -t 117.50.75.30:8080/cfpif/openpicl.studio:{{tag}} .
    docker push 117.50.75.30:8080/cfpif/openpicl.studio:latest
    docker push 117.50.75.30:8080/cfpif/openpicl.studio:{{tag}}