apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-website
  labels:
    app: website
spec:
  type: {{ .Values.website.service.type }}
  selector:
    app: website
  ports:
    - name: http
      port: {{ .Values.website.service.port }}
      targetPort: 3004