set windows-shell := ["powershell.exe"]
export RUST_BACKTRACE := "1"

# 展示可用的命令
@just:
    just --list

# 运行 Rust 测试
test:
    cargo test

# 运行 Cargo Check
check:
    cargo check -p nebula
    cargo check -p nebula-core
    cargo check -p nebula-protos
    cargo check -p photensor
    cargo check -p photensor-burn
    cargo check -p photensor-core
    cargo check -p photensor-hw
    cargo check -p photensor-macros
    cargo check -p photensor-sim

# 调用 rustfmt 工具
fmt:
    cargo fmt --all -- --check

# 调用 clippy 工具
clippy:
    cargo clippy -p nebula -- -D warnings
    cargo clippy -p nebula-core -- -D warnings
    cargo clippy -p nebula-protos -- -D warnings
    cargo clippy -p photensor -- -D warnings
    cargo clippy -p photensor-burn -- -D warnings
    cargo clippy -p photensor-core -- -D warnings
    cargo clippy -p photensor-hw -- -D warnings
    cargo clippy -p photensor-macros -- -D warnings
    cargo clippy -p photensor-sim -- -D warnings

# 清理构建产物
clean:
    cargo clean

# 生成 Nexus Repository Token
token password:
    echo -n "admin:{{password}}" | base64

# 登录 Nexus Cargo 制品库
login token:
    echo CARGO_REGISTRIES_CARGO_HOSTED_TOKEN={{token}}

# 推送 crate
publish crate:
    cargo publish --package {{crate}}
