studio:
  replicas: 1
  image:
    repository: 117.50.75.30:8080/cfpif/openpicl.studio
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000

webide:
  replicas: 1
  image:
    repository: 117.50.75.30:8080/cfpif/openpicl.webide
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3002

website:
  replicas: 1
  image:
    repository: 117.50.75.30:8080/cfpif/openpicl.website
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3004

docs:
  replicas: 1
  image:
    repository: 117.50.75.30:8080/cfpif/openpicl.docs
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80