[package]
name = "nebula"
description = "Nebula, a CLI tool"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
publish.workspace = true
readme = "README.md"

[package.metadata]
publish = ["cargo-hosted"]

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
colored.workspace = true

nebula-core = { path = "../nebula-core", version = "0.1.0", registry = "cargo-hosted" }
nebula-protos = { path = "../nebula-protos", version = "0.1.0", registry = "cargo-hosted" }