apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-studio
  labels:
    app: studio
spec:
  type: {{ .Values.studio.service.type }}
  selector:
    app: studio
  ports:
    - name: http
      port: {{ .Values.studio.service.port }}
      targetPort: 3000