apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webide
  labels:
    app: webide
spec:
  type: {{ .Values.webide.service.type }}
  selector:
    app: webide
  ports:
    - name: http
      port: {{ .Values.webide.service.port }}
      targetPort: 3002