apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webide
  labels:
    app: webide
spec:
  replicas: {{ .Values.webide.replicas }}
  selector:
    matchLabels:
      app: webide
  template:
    metadata:
      labels:
        app: webide
    spec:
      containers:
        - name: webide
          image: "{{ .Values.webide.image.repository }}:{{ .Values.webide.image.tag }}"
          imagePullPolicy: {{ .Values.webide.image.pullPolicy }}
          ports:
            - containerPort: 3002