set windows-shell := ["powershell.exe"]
export RUST_BACKTRACE := "1"

# 展示可用的命令
@just:
    just --list

# 登录 CNB 制品库
login:
    docker login -u cnb docker.cnb.cool

# 构建并推送制品
publish tag:
    docker build -t docker.cnb.cool/igipme/opif/openpicl/docs:latest -t docker.cnb.cool/igipme/opif/openpicl/docs:{{tag}} .
    docker push docker.cnb.cool/igipme/opif/openpicl/docs:latest
    docker push docker.cnb.cool/igipme/opif/openpicl/docs:{{tag}}